name: Apple Develop Build

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy-ios:
    runs-on: macos-latest
    environment: Develop
    steps:
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Set up git and fetch all history for all branches and tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Setup dependencies
        run: |
          bundle config set path 'vendor/bundle' 
          bundle install
      - name: Build and Deploy to TestFlight
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_TEAM_NAME: ${{ secrets.APPLE_TEAM_NAME }}
          MATCH_URL: ${{ secrets.MATCH_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: 
          bundle exec fastlane release
